### ISSUE TITLE
Hospitality Content

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#35]
Via Buzz: 

I've perused the new website and it is VERY VERY impressive! It is so concise and well organized that it is hard to believe that everything on the current site was included. (double-checking whether such could possibly be the case I do wonder about items at the bottom of the current page. I don't immediately see "Rent our Facilities" or "Guidelines for Committee Clerks" for example)

Now, for the main point of the email. I'm a new clerk of the Hospitality Committee. Attached is a picture of a simple html page that I keep on my home computer with links to various documents that I want to have ready at hand with information on the Hospitality Committee. What are the chances that a web page like this, and the documents it links to, could be put on GitHub so that it could be accessed by Hospitality members (and, possibly, only them)? It would be very useful for committee members, and they have requested that such information be easily available on the web rather than buried in myriad emails.

![image](https://user-images.githubusercontent.com/223778/55095947-649bfa80-508f-11e9-857e-0164341eaf58.png)

**Comment by radiolevity** [comment]
Okay, new commit includes a (relatively robust) framework for this page. It is generated off of a data file, so Buzz should only have to edit data/hospitality.yml and add relevant files to assets/hospitality/ in order to update the page. I'm not completely sure how that meshes with the current workflow; can we give out access to only specific directories, such as with submodule? (or webhooks, according to google)

For now, I will bring this up with Buzz and table this functionality until after the release.
